routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home',  'HomeController@index');
Route::get('/about',  'HomeController@about')->name('about');
Route::get('/sponsorship',  'HomeController@sponsorship')->name('sponsorship');
Route::get('/winners',  'HomeController@winners')->name('winners');
Route::get('/highlights',  'HomeController@highlights')->name('highlights');
Route::get('/sponsorship',  'HomeController@sponsorship')->name('sponsorship');
Route::get('/contact',  'HomeController@contact')->name('contact');
Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/categories/list',  'HomeController@listcategories')->name('listcategories');

Auth::routes();

Route::resource('contacts', 'ContactController')->only([
    'store'
]);

Route::get('nominees/terms', 'NomineeController@term_condition')->name('nominees.terms');
Route::resource('nominees', 'NomineeController')->only([
    'create', 'show', 'store'
]);

Route::group( ['middleware' => ['auth']], function() {

   


    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');
    
    Route::get('/profile',  'HomeController@profile')->name('profile');
    Route::get('/profile/edit',  'HomeController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'HomeController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'HomeController@profile_update')->name('profile.update');
    Route::put('/profile/password/update',  'HomeController@profile_pw_update')->name('profile.pw_update');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');
    // Route::resource('posts', 'PostController');

    Route::resource('nominees', 'NomineeController')->except([
        'create', 'show', 'store'
    ]);

    Route::resource('contacts', 'ContactController')->except([
        'store'
    ]);

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser');
    Route::get('datatables/getNominee', 'DatatablesController@getNominee');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Activitylog\Traits\LogsActivity;

use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\HasMedia;

class User extends Authenticatable implements HasMedia
{
    use Notifiable;
    use HasRoles;
    use LogsActivity;
    use HasMediaTrait;

    protected static $logAttributes = ['name', 'email', 'password', 'username']; //disable if dont want allow username as auth
    // protected static $logAttributes = ['name', 'email', 'password'];
    protected static $logOnlyDirty = true;
    protected static $logName = 'users';
    protected static $ignoreChangedAttributes = ['updated_at', 'remember_token'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username',//disable if dont want allow username as auth
        // 'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Traits\Authorizable;
use Auth;
use App\User;
use App\Role;
use App\Permission;
use Spatie\Activitylog\Models\Activity;

class UserController extends Controller
{
    use Authorizable;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'username' => 'required|string|max:20|unique:users', //disable if dont want allow username as auth
            'password' => 'required|confirmed|min:6',
            'roles' => 'required|min:1'
        ]);

        // hash password
        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {
            $this->syncPermissions($request, $user);
            flash('User has been created.');
        } else {
            flash()->error('Unable to create user.');
        }

        return redirect()->route('users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        $logs = Activity::where('causer_id', $id)->latest()->limit(100)->get();
        return view('users.show', compact('user', 'logs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        

        return view('users.edit', compact('user', 'roles'));
    }

    public function edit_pw($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit_pw', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users,email,' . $id,
            'username' => 'required|unique:users,username,' . $id, //disable if dont want allow username as auth
            'roles' => 'required|min:1'
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // Update user
        $user->fill($request->except('roles', 'permissions', 'password'));

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        // Handle the user roles
        $this->syncPermissions($request, $user);

        $user->save();
        flash()->success('User has been updated.');
        return redirect()->route('users.show', $id);
    }

    public function update_pw(Request $request, $id)
    {
        $this->validate($request, [
            'password' => 'required|confirmed|min:6',
        ]);

        // Get the user
        $user = User::findOrFail($id);

        // check for password change
        if($request->get('password')) {
            $user->password = bcrypt($request->get('password'));
        }

        $user->save();
        flash()->success('User password has been updated.');
        return redirect()->route('users.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ( Auth::user()->id == $id ) {
            flash()->warning('Deletion of currently logged in user is not allowed :(')->important();
            return redirect()->back();
        }

        if( User::findOrFail($id)->delete() ) {
            flash()->success('User has been deleted');
        } else {
            flash()->success('User not deleted');
        }

        return redirect()->back();
    }

    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);
        return $user;
    }
}

resources/views/users/create.blade.php
@extends('layouts.dashboard.master')

@section('title', 'User Management')
@section('subtitle', 'Create')

@section('content')

<div class="row">
    <div class='col-lg-12'>

    {{ Form::open(array('url' => 'users')) }}

    <div class="form-group">
        {{ Form::label('email', 'E-Mail Address') }}
        {{ Form::email('email', null, array('class' => 'form-control', 'required')) }}
    </div>

    {{--  disable if dont want allow username as auth  --}}
    <div class="form-group">
        {{ Form::label('username', 'Username') }}
        {{ Form::text('username', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }}
        {{ Form::password('password', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('password_confirmation', 'Confirm Password') }}
        {{ Form::password('password_confirmation', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('roles_label', 'Roles') }}
        @foreach($roles as $role)
        <br />
        {{ Form::checkbox('roles[]', $role->id) }}
        {{ Form::label('roles', $role->name) }} 
        @endforeach
    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary btn-tools btn-xxx')) }}

    {{ Form::close() }}

    </div>
</div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.dashboard.master')

@section('title', 'User Management')
@section('subtitle', 'Edit')

@section('content')

<div class="row">
    <div class='col-lg-12'>

    {{ Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'PUT']) }}

    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', null, array('class' => 'form-control', 'required')) }}
    </div>

    {{--  disable if dont want allow username as auth  --}}
    <div class="form-group">
        {{ Form::label('username', 'Username') }}
        {{ Form::text('username', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'E-Mail Address') }}
        {{ Form::email('email', null, array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('roles_label', 'Roles') }}
        @foreach($roles as $role)
        <br />
        {{ Form::checkbox('roles[]', $role->id) }}
        {{ Form::label('roles', $role->name) }} 
        @endforeach
    </div>

    <a class="btn btn-link" href="{{ url()->previous() }}">Back</a>
    {{ Form::submit('Save', array('class' => 'btn btn-primary btn-tools btn-xxx')) }}

    {{ Form::close() }}

    </div>
</div>

@endsection

resources/views/users/edit_pw.blade.php
@extends('layouts.dashboard.master')

@section('title', 'User Management')
@section('subtitle', 'Edit Password')

@section('content')

<div class="row">
    <div class='col-lg-12'>

    {{ Form::model($user, ['route' => ['users.update_pw', $user->id], 'method' => 'PUT']) }}

    <div class="form-group">
        {{ Form::label('password', 'Password') }}
        {{ Form::password('password', array('class' => 'form-control', 'required')) }}
    </div>

    <div class="form-group">
        {{ Form::label('password_confirmation', 'Confirm Password') }}
        {{ Form::password('password_confirmation', array('class' => 'form-control', 'required')) }}
    </div>

    <a class="btn btn-link" href="{{ url()->previous() }}">Back</a>
    {{ Form::submit('Update', array('class' => 'btn btn-primary btn-tools btn-xxx')) }}

    {{ Form::close() }}

    </div>
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.dashboard.master')

@section('title', 'User Management')

@section('content')

<div class="card">
    <div class="card-body">
        @can('add_users')
            <a href="{{route('users.create')}}" class="btn btn-success">
                <i class="fas fa-plus"></i> New
            </a>
        @endcan
    </div>
</div>

<br />
<table id="users-table" class="table table-bordered">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Email</th>
        <th>Roles</th>
        <th>Created At</th>
        <th>Action</th>
    </tr>
    </thead>
</table>

@endsection

@section('js')
@parent

<script>
    $(function () {
        $('#users-table').DataTable({
            serverSide: true,
            processing: true,
            ajax: '/datatables/getUser',
            columns: [
                {data: 'DT_Row_Index', orderable: false, searchable: false},
                {data: 'name'},
                {data: 'email'},
                {data: 'roles', name: 'roles.name', orderable: false},
                {data: 'created_at'},
                {data: 'action', orderable: false, searchable: false}
            ]
        });
    });
</script>

@endsection

resources/views/users/show.blade.php
@extends('layouts.dashboard.master')

@section('title', 'User Management')
@section('subtitle', '')

@section('content')

<div class="row">
    <div class='col-lg-12'>

    <table class="table table-bordered">
        <tr>
            <td>Name</td>
            <td>{{$user->name}}</td>
        </tr>
        {{--  disable if dont want allow username as auth  --}}
        <tr>
                <td>Username</td>
                <td>{{$user->username}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{$user->email}}</td>
        </tr>
        <tr>
            <td>Roles</td>
            <td>
                @foreach($user->roles as$role)
                    {{$role->name}} <br>
                @endforeach
            </td>
        </tr>
    </table>

    <a class="btn btn-link" href="{{ route('users.index') }}">Back</a>
    <a class="btn btn-info" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">View Activity Log</a>

    @can('edit_users')
    <a class="btn btn-warning" href="{{route('users.edit', $user->id)}}">Edit</a>
    <a class="btn btn-warning" href="{{route('users.edit_pw', $user->id)}}">Change Password</a>
    @endcan

    @can('delete_users')
    <a class="btn btn-xs btn-danger" data-method="delete" data-confirm="confirm" href="{{ route('users.destroy', $user->id) }}">Delete</a>
    @endcan


    </div>
</div>

<div class="row collapse" id="collapseExample">
        <div class='col-lg-12'>
            <hr />
            <h3>Log Activity</h3>
            <table class="table table-bordered">
                    <tr>
                        <td>Time</td>
                        <td>Model Changes</td>
                        <td>Description</td>
                        <td>Model ID</td>
                    </tr>
                    @foreach($logs as $log)
                    <tr>
                        <td>
                            {{$log->created_at}}
                        </td>
                        <td>
                            {{$log->subject_type}}
                        </td>
                        <td>
                            {{$log->description}}
                        </td>
                        <td>
                            {{$log->subject_id}}
                        </td>
                    </tr>
                    @endforeach
                </table>
        </div>
</div>

@endsection