routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home',  'HomeController@index');
Route::get('/about',  'HomeController@about')->name('about');
Route::get('/sponsorship',  'HomeController@sponsorship')->name('sponsorship');
Route::get('/winners',  'HomeController@winners')->name('winners');
Route::get('/highlights',  'HomeController@highlights')->name('highlights');
Route::get('/sponsorship',  'HomeController@sponsorship')->name('sponsorship');
Route::get('/contact',  'HomeController@contact')->name('contact');
Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/categories/list',  'HomeController@listcategories')->name('listcategories');

Auth::routes();

Route::resource('contacts', 'ContactController')->only([
    'store'
]);

Route::get('nominees/terms', 'NomineeController@term_condition')->name('nominees.terms');
Route::resource('nominees', 'NomineeController')->only([
    'create', 'show', 'store'
]);

Route::group( ['middleware' => ['auth']], function() {

   


    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');
    
    Route::get('/profile',  'HomeController@profile')->name('profile');
    Route::get('/profile/edit',  'HomeController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'HomeController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'HomeController@profile_update')->name('profile.update');
    Route::put('/profile/password/update',  'HomeController@profile_pw_update')->name('profile.pw_update');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');
    // Route::resource('posts', 'PostController');

    Route::resource('nominees', 'NomineeController')->except([
        'create', 'show', 'store'
    ]);

    Route::resource('contacts', 'ContactController')->except([
        'store'
    ]);

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser');
    Route::get('datatables/getNominee', 'DatatablesController@getNominee');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');
});

resources/views/layouts/dashboard/content.blade.php
<div class="container-fixed container-fluid">
    <div class="row">

        <nav class="col-md-2 d-none d-md-block sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('dashboard')}}">
                            Dashboard
                        </a>
                    </li>

                    @can('view_nominees')
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('nominees.index')}}">
                            Nominee Management
                        </a>
                    </li>
                    @endcan

                    @can('view_users')
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('users.index')}}">
                            Users Management
                        </a>
                    </li>
                    @endcan

                    @can('view_categories')
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('categories.index')}}">
                            Category Management
                        </a>
                    </li>
                    @endcan

                    @can('view_roles')
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('roles.index')}}">
                            Roles & Permission
                        </a>
                    </li>
                    @endcan

                </ul>

            </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
            <!-- Page Heading -->
            <h1 class="my-4">@yield('title')
                <small class="text-secondary">@yield('subtitle')</small>
            </h1>


            @include('flash::message')
            @include('shared/_error')
            @yield('content')
        </main>
    </div>

</div>

resources/views/layouts/dashboard/master.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Volunteer Malaysia Awards 2017">
    <meta name="author" content="Volunteer Malaysia">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>
    <link rel="shortcut icon" href="/img/logo/footerlogo.png" />
    <link href="{{ mix('/css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    <link href="{!! asset('css/custom.css') !!}" media="all" rel="stylesheet" type="text/css" />

    @yield('css')

  </head>

  <body>

    @include('cookieConsent::index')

    @include('layouts.basic.navbar')
    <!-- Page Content -->
    @include('layouts.dashboard.content')
    <!-- /.container -->
    {{-- @include('layouts.basic.footer') --}}


    @include('shared._delete_confirm')

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <script src="{{ mix('/js/app.js') }}"></script>
  

    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.js"></script>
    @yield('js')

  </body>

</html>