routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home',  'HomeController@index');
Route::get('/about',  'HomeController@about')->name('about');
Route::get('/sponsorship',  'HomeController@sponsorship')->name('sponsorship');
Route::get('/winners',  'HomeController@winners')->name('winners');
Route::get('/highlights',  'HomeController@highlights')->name('highlights');
Route::get('/sponsorship',  'HomeController@sponsorship')->name('sponsorship');
Route::get('/contact',  'HomeController@contact')->name('contact');
Route::get('locale/{locale}', function ($locale) {
    \Session::put('locale', $locale);
    return redirect()->back();
})->name('locale');

Route::get('/categories/list',  'HomeController@listcategories')->name('listcategories');

Auth::routes();

Route::resource('contacts', 'ContactController')->only([
    'store'
]);

Route::get('nominees/terms', 'NomineeController@term_condition')->name('nominees.terms');
Route::resource('nominees', 'NomineeController')->only([
    'create', 'show', 'store'
]);

Route::group( ['middleware' => ['auth']], function() {

   


    Route::get('/dashboard',  'HomeController@dashboard')->name('dashboard');
    
    Route::get('/profile',  'HomeController@profile')->name('profile');
    Route::get('/profile/edit',  'HomeController@profile_edit')->name('profile.edit');
    Route::get('/profile/password',  'HomeController@profile_edit_pw')->name('profile.edit_pw');
    Route::put('/profile/update',  'HomeController@profile_update')->name('profile.update');
    Route::put('/profile/password/update',  'HomeController@profile_pw_update')->name('profile.pw_update');
    
    Route::resource('users', 'UserController');
    Route::get('/users/password/{id}/edit', 'UserController@edit_pw')->name('users.edit_pw');    
    Route::put('/users/password/{id}', 'UserController@update_pw')->name('users.update_pw');    

    Route::resource('roles', 'RoleController');
    Route::resource('categories', 'CategoryController');
    // Route::resource('posts', 'PostController');

    Route::resource('nominees', 'NomineeController')->except([
        'create', 'show', 'store'
    ]);

    Route::resource('contacts', 'ContactController')->except([
        'store'
    ]);

    //datatables
    Route::get('datatables/getUser', 'DatatablesController@getUser');
    Route::get('datatables/getNominee', 'DatatablesController@getNominee');


    //upload 
    Route::post('upload/image', 'UploadController@upload_image')->name('upload.image');
});

resources/views/shared/_delete_confirm.blade.php
@section('css')
    @parent
@endsection

@section('js')
    @parent
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

    <script>
        window.csrfToken = '<?php echo csrf_token(); ?>';
    </script>

    <script>
        (function() {

            var delete_confirm = {
                initialize: function() {
                    this.registerEvents();
                },

                registerEvents: function() {
                    $('body').on('click', 'a[data-method]', this.handleMethod);
                },

                handleMethod: function(e) {
                    e.preventDefault();
                    var link = $(this);
                    var httpMethod = link.data('method').toUpperCase();
                    var form;

                    // If the data-method attribute is not PUT or DELETE,
                    // then we don't know what to do. Just ignore.
                    if ( $.inArray(httpMethod, ['PUT', 'DELETE']) === - 1 ) {
                        return;
                    }

                    // Allow user to optionally provide data-confirm="Are you sure?"
                    // if ( link.data('confirm') ) {
                    //     if ( ! delete_confirm.verifyConfirm(link) ) {
                    //         return false;
                    //     }
                    // }
                    // form = delete_confirm.createForm(link);
                    // form.submit();
                    //
                    // e.preventDefault();

                    delete_confirm.verifyConfirm(link)
                        .done(function () {
                            form = delete_confirm.createForm(link)
                            form.submit()
                        })
                },

                verifyConfirm: function(link) {
                    // return confirm(link.data('confirm'));
                    //return confirm('Are you sure?');
                    var confirm = new $.Deferred();

                    bootbox.confirm('Are you sure?', function(result) {
                        if (result) {
                            confirm.resolve(link);
                        } else {
                            confirm.reject(link);
                        }
                    })

                    return confirm.promise()
                },

                createForm: function(link) {
                    var form =
                        $('<form>', {
                            'method': 'POST',
                            'action': link.attr('href')
                        });

                    var token =
                        $('<input>', {
                            'name': '_token',
                            'type': 'hidden',
                            'value': window.csrfToken
                        });

                    var hiddenInput =
                        $('<input>', {
                            'name': '_method',
                            'type': 'hidden',
                            'value': link.data('method')
                        });

                    return form.append(token, hiddenInput)
                        .appendTo('body');
                }
            };

            delete_confirm.initialize();

        })();
    </script>

@endsection

resources/views/shared/_error.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/shared/_permissions.blade.php
<div class="card">
    <div class="card-header" id="{{ str_slug($title) }}">
        <h5 class="mb-0">
            <button type="button" class="btn btn-link float-left" data-toggle="collapse" data-target="#dd-{{ str_slug($title) }}">
                {{ $title or 'Override Permissions' }}
            </button>
        </h5>
    </div>

    <div id="dd-{{ str_slug($title) }}" class="collapse  {{ $closed or 'show' }}"  data-parent="#accordion">
        <div class="card-body">
            <div class="row">
                @foreach($permissions as $perm)
                    <?php
                    $per_found = null;

                    if( isset($role) ) {
                        $per_found = $role->hasPermissionTo($perm->name);
                    }

                    if( isset($user)) {
                        $per_found = $user->hasDirectPermission($perm->name);
                    }
                    ?>

                    <div class="col-md-3">
                        <div class="checkbox">
                            <label class="{{ str_contains($perm->name, 'delete') ? 'text-danger' : '' }}">
                                {!! Form::checkbox("permissions[]", $perm->name, $per_found, isset($options) ? $options : []) !!} {{ $perm->name }}
                            </label>
                        </div>
                    </div>
                @endforeach

                    @if($btn_hide != true)
                            <div class="col-md-12">
                                @can('edit_roles')
                                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                                @endcan

                                <a class="btn btn-danger" data-method="delete" data-confirm="confirm" href="{{ route('roles.destroy', $role->id) }}">Delete</a>
                            </div>
                    @endif
            </div>
        </div>
    </div>
</div>

resources/views/shared/_popup.blade.php
@if(session('popup'))

    {{-- Invoke from reject term --}}
    @if(session('popup') == 'reject')
        <div id="loadModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="green-bg d-flex justify-content-center p-2" style="position:relative;">
                        <i class="far fa-thumbs-up white-text m-4" style="font-size:5em"></i>
                        <a href="" data-dismiss="modal" class="close"  aria-label="Close" style="position:absolute; top:10px; right:15px">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </div>
                    <div class="modal-body text-center">
                        <h3 class="green-text pt-3">Thank You For Creating Project!</h3>
                        <p>You have finished creating a project, it will be revised by Admin for approval. You will get notification via email after the project successfully published.</p>
                    </div>
                    <div class="modal-footer d-flex justify-content-center">
                        <a href="" data-dismiss="modal" class="btn btn-green" style="width:200px;">OK</a>
                    </div>
                </div>
            </div>
        </div>
    @endif


    {{-- Invoke from after nominee --}}
    @if(session('popup') == 'register')
        <div id="loadModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="green-bg d-flex justify-content-center p-2" style="position:relative;">
                        <i class="far fa-thumbs-up white-text m-4" style="font-size:5em"></i>
                        <a href="" data-dismiss="modal" class="close"  aria-label="Close" style="position:absolute; top:10px; right:15px">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </div>
                    <div class="modal-body text-center">
                        <h3 class="green-text pt-3">Thank You For Creating Project!</h3>
                        <p>You have finished creating a project, it will be revised by Admin for approval. You will get notification via email after the project successfully published.</p>
                    </div>
                    <div class="modal-footer d-flex justify-content-center">
                        <a href="" data-dismiss="modal" class="btn btn-green" style="width:200px;">OK</a>
                    </div>
                </div>
            </div>
        </div>
    @endif


@endif



@section('js')
@parent 

<script type="text/javascript">
    $(window).on('load',function(){
        $('#loadModal').modal('show');
    });
</script>

@endsection

resources/views/shared/_table_action.blade.php
@can('view_'.$url)
<a class="btn btn-xs btn-success" href="{{route($url.'.show', $model->id)}}">Show</a>
@endcan

@can('edit_'.$url)
<a class="btn btn-xs btn-warning" href="{{route($url.'.edit', $model->id)}}">Edit</a>
@endcan

@can('delete_'.$url)
<a class="btn btn-xs btn-danger" data-method="delete" data-confirm="confirm" href="{{ route($url.'.destroy', $model->id) }}">Delete</a>
@endcan

resources/views/shared/_upload_image.blade.php
{!! Form::open(['url' => route('upload.image'), 'files' => 'true']) !!}

    <div class="input-group mb-3">
        <div class="custom-file">
            {{ Form::file('image' ,['class' => "custom-file-input", 'id' => "inputGroupFile01", 'accept'=>"image/*"]) }}
            <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
        </div>
    </div>


    {!! Form::hidden('model_name', $model_name) !!}    
    {!! Form::hidden('model_id', $model_id) !!}    
    {!! Form::hidden('collection', $collection) !!}    

    {!! Form::submit('Upload Image', ['class' => 'btn btn-primary btn-block']) !!}    

{!! Form::close() !!}

@section('js')
@parent

<script>
    $('#inputGroupFile01').on('change',function(){
        var fileName = $(this).val();
        $(this).next('.custom-file-label').html(fileName);
    })
</script>

@endsection